import { NavbarWhite } from '@/components/ui/NavbarWhite';
import localFont from 'next/font/local';
import './globals.css'
const poppins = localFont({ src: '../../public/fonts/Poppins-Regular.woff2' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es" className='scroll-smooth'>
      <body className={`container h-[2000px] mx-auto max-w-[1920px] ${poppins.className} overflow-x-hidden`}>
        <header>
          <NavbarWhite />
        </header>       
        {children}
      </body>
    </html>
  )
}
